trainingInput:
  scaleTier: BASIC_GPU
  hyperparameters:
    enableTrialEarlyStopping: True
    hyperparameterMetricTag: auc
    maxTrials: 60
    maxParallelTrials: 2
    params:
    - parameterName: dropout
      type: DOUBLE
      minValue: 0.2
      maxValue: 0.6
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: learning-rate
      type: DOUBLE
      minValue: 0.0001
      maxValue: 0.01
      scaleType: UNIT_REVERSE_LOG_SCALE
    - parameterName: first-layer-size
      type: INTEGER
      minValue: 256
      maxValue: 8192
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: num-layers
      type: INTEGER
      minValue: 1
      maxValue: 10
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: scale-factor
      type: DOUBLE
      minValue: 0.3
      maxValue: 0.99
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: cpc-embedding-dim
      type: INTEGER
      minValue: 5
      maxValue: 100
      scaleType: UNIT_LINEAR_SCALE
